export const ADD_CONTACT = 'ADD_CONTACT';
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT='REMOVE_CONTACT'
export const SELECT_ALL_CONTACTS='SELECT_ALL_CONTACTS'
export const CLEAR_ALL_CONTACTS='CLEAR_ALL_CONTACTS'
export const DELETE_ALL_CONTACTS='DELETE_ALL_CONTACTS'